### ISSUE TITLE
max rested xp pls!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by DdDBrujah420** [Arxareon/RemainingXP#1]
I really love what you're doing with the mod.  Is there a way to add a feature or something to say that you're at max rested xp? 267% doesn't mean anything when leveling up.  Would be much appreciated

**Comment by Arxareon** [comment]
Rested XP goes up to 150% of the full required XP amount at your current level (presumably) to reach the next level. Let's say, if you're level 30, you'll need 45 370 XP to reach level 31. So, while at 30, you can collect and store up to 68 055 Rested XP.

Remaining XP (currently) displays the Rested XP percentage compared to the XP needed to reach the next level, instead of the % of the max Rested XP you can get at your current level. Displaying this extra info shouldn't be too difficult, I'll see if I can get that worked in with the next update. It'll probably be included in the detailed tooltip, but we'll see.

Thanks for the feedback!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Arxareon** [comment]
I've added the information to the enhanced XP tooltip as well as improved chat notification messages to also tell you if you've already got max Rested XP (150% of the total XP needed to level up).

It will be included in the next version release which should arrive soon. There is a lot of work and a couple of errors to iron out so it might take a bit more than a day or two. Thanks for understanding!
